import React from 'react';
import { NewsItem } from './types';

interface NewsCardProps {
  item: NewsItem;
  variant?: 'hero' | 'standard' | 'sidebar';
  onClick: (item: NewsItem) => void;
}

export const NewsCard: React.FC<NewsCardProps> = ({ item, variant = 'standard', onClick }) => {
  
  // The political cartoon "Panel" look with slightly rougher borders
  const panelClasses = "relative bg-white border-[4px] border-ink shadow-[8px_8px_0px_0px_rgba(42,42,42,1)] hover:shadow-[12px_12px_0px_0px_rgba(42,42,42,1)] hover:-translate-y-1 transition-all duration-300 cursor-pointer overflow-hidden group";
  
  // Simulated speech bubble text (if not generated by backend yet, use category or snippet)
  const speechText = item.description.length > 80 
    ? item.description.substring(0, 80) + "..." 
    : item.description;

  // -- HERO VARIANT (Big Editorial Cartoon) --
  if (variant === 'hero') {
    return (
      <div onClick={() => onClick(item)} className={`${panelClasses} mb-12 transform rotate-[-1deg] hover:rotate-0 transition-transform`}>
        
        {/* Top Label (e.g. "The Economy") */}
        <div className="absolute top-0 left-0 bg-ink text-white px-4 py-1 font-comic text-sm tracking-widest z-30 border-b-[3px] border-r-[3px] border-white">
          {item.category.toUpperCase()}
        </div>

        <div className="relative h-[550px] bg-wash-blue/20 overflow-hidden border-b-[4px] border-ink">
             {/* The "Cartoon" Image */}
             <img 
                src={item.image || `https://picsum.photos/seed/${item.id}/1200/800`} 
                alt={item.title}
                className="w-full h-full object-cover watercolor-filter brightness-110 contrast-125 sepia-[0.2]"
             />
             
             {/* Speech Bubble Overlay - positioned more dynamically */}
             <div className="absolute top-[10%] right-[5%] max-w-sm z-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
                <div className="bg-white border-[3px] border-ink rounded-[2rem] p-6 shadow-sm relative text-center transform rotate-2 hover:scale-105 transition-transform">
                    <p className="font-comic text-xl md:text-2xl leading-tight text-ink">
                        "{speechText}"
                    </p>
                    {/* Bubble Tail */}
                    <div className="absolute bottom-[-20px] left-1/3 w-0 h-0 border-l-[20px] border-l-transparent border-r-[0px] border-r-transparent border-t-[25px] border-t-ink transform skew-x-[-20deg]"></div>
                    <div className="absolute bottom-[-14px] left-[35%] w-0 h-0 border-l-[16px] border-l-transparent border-r-[0px] border-r-transparent border-t-[21px] border-t-white transform skew-x-[-20deg]"></div>
                </div>
             </div>

             {/* Satirical Label on Image (like labeling a sinking ship) */}
             <div className="absolute bottom-[20%] left-[10%] bg-white/90 border-2 border-ink px-2 py-0.5 transform -rotate-3 shadow-sm z-20 group-hover:rotate-0 transition-transform">
                <span className="font-comic text-xs font-bold text-ink">THE INDUSTRY &rarr;</span>
             </div>

             {/* Artist Signature */}
             <div className="absolute bottom-3 right-4 font-comic text-ink/80 text-xl transform -rotate-6 z-20 mix-blend-multiply">
                Varvel-Bot '24
             </div>
        </div>

        {/* Bottom Caption Box (Editorial Style) */}
        <div className="bg-paper p-6 text-center relative">
             <div className="flex items-center justify-center space-x-2 mb-2 opacity-60">
                <span className="h-px w-8 bg-ink"></span>
                <span className="font-editorial italic text-xs uppercase tracking-widest">{item.source} • {item.date}</span>
                <span className="h-px w-8 bg-ink"></span>
             </div>
             <h2 className="font-editorial font-black text-3xl md:text-5xl text-ink uppercase leading-[0.9] tracking-tight group-hover:text-wash-blue transition-colors duration-300">
                {item.title}
             </h2>
        </div>
      </div>
    );
  }

  // -- SIDEBAR VARIANT --
  if (variant === 'sidebar') {
      return (
        <div onClick={() => onClick(item)} className="py-4 border-b-2 border-dashed border-ink/30 last:border-0 group cursor-pointer hover:bg-wash-yellow/20 px-2 transition-colors relative">
            <div className="flex flex-col">
                <div className="flex items-center justify-between mb-1">
                    <span className="font-comic font-bold text-xs text-wash-red">{item.category.toUpperCase()}</span>
                    <span className="font-hand text-xs text-gray-500">{item.date}</span>
                </div>
                <h3 className="font-editorial font-bold text-lg leading-tight mb-1 group-hover:underline decoration-wavy decoration-ink">
                    {item.title}
                </h3>
            </div>
        </div>
      )
  }

  // -- STANDARD VARIANT (Standard Panel) --
  return (
    <div onClick={() => onClick(item)} className={`${panelClasses} flex flex-col h-full`}>
      
      {/* Image Area */}
      <div className="relative h-56 overflow-hidden bg-gray-100 border-b-[4px] border-ink">
         <img 
            src={item.image || `https://picsum.photos/seed/${item.id}/600/400`} 
            alt={item.title}
            className="w-full h-full object-cover watercolor-filter group-hover:scale-110 transition-transform duration-700 contrast-125"
         />
         
         {/* Small Speech Bubble */}
         <div className="absolute top-3 right-3 max-w-[180px] transition-transform duration-300 group-hover:-translate-y-1">
            <div className="bg-white border-2 border-ink rounded-[15px] p-2 shadow-sm relative">
                <p className="font-comic text-xs leading-tight text-center">
                    "{item.category === 'breaking' ? 'READ THIS!' : 'HMM...'}"
                </p>
                 <div className="absolute bottom-[-6px] left-2 w-3 h-3 bg-white border-r-2 border-b-2 border-ink transform rotate-45"></div>
            </div>
         </div>
      </div>

      {/* Caption/Story Area */}
      <div className="p-4 bg-paper flex-grow flex flex-col justify-between group-hover:bg-yellow-50 transition-colors">
          <div>
            <h3 className="font-editorial font-bold text-xl leading-[1.1] mb-2 group-hover:text-wash-red transition-colors">
                {item.title}
            </h3>
            <p className="font-editorial italic text-gray-600 text-sm line-clamp-3 leading-relaxed border-l-2 border-ink/20 pl-3 group-hover:border-wash-red transition-colors">
                {item.description}
            </p>
          </div>
          
          <div className="mt-4 pt-2 border-t-2 border-ink/10 flex justify-between items-center">
              <span className="font-comic text-xs text-gray-400 uppercase tracking-wider">{item.source}</span>
              <div className="bg-ink text-white px-2 py-0.5 text-xs font-bold transform rotate-2 group-hover:rotate-0 transition-transform border border-transparent group-hover:border-white">
                  PAGE {item.id}
              </div>
          </div>
      </div>
    </div>
  );
};
